title: Dev As Pros
email: devaspros@gmail.com
description: >-
  Desarrollo de Software para Pequeñas y Medianas Empresas
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.devaspros.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: devaspros
github_username:  devaspros

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# SEO PLUGIN
twitter:
  username: devaspros
  card: summary
lang: es
logo: /images/devaspros-logo-transparency.png
social:
  name: Dev As Pros
  links:
    - https://www.facebook.com/devaspros/
    - https://twitter.com/devaspros
    - https://www.instagram.com/devaspros/
    - https://www.linkedin.com/company/devaspros/
    - https://github.com/devaspros/