title: Desarrollo de Software | Web Apps |Dev As Pros
email: devaspros@gmail.com
description: >-
  Desarrollo de Software para Pequeñas y Medianas Empresas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devaspros.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: devaspros
github_username:  devaspros

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
